# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
cache: cocoapods
podfile: example/Podfile
before_install:
 - rvm use system
 - sudo gem install bundler
 - sudo gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - sudo gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
 - sudo gem install cocoapods --pre # Since Travis is not always on latest version


script:
- pod spec lint --quick
#- set -o pipefail && xcodebuild -workspace Example/MMSProfileImagePicker.xcworkspace -list | xcpretty;
#- set -o pipefail && xcodebuild clean build -workspace Example/MMSProfileImagePicker.xcworkspace -scheme Pods-MMSProfileImagePicker_Example -sdk iphonesimulator PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=ios Simulator,name=iphone 6,OS=9.3' | xcpretty;
#- set -o pipefail && xcodebuild clean build -workspace Example/MMSProfileImagePicker.xcworkspace -scheme Pods-MMSProfileImagePicker_Tests -sdk iphonesimulator PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=ios Simulator,name=iphone 6,OS=9.3' | xcpretty;
#- set -o pipefail && xcodebuild clean test -workspace Example/MMSProfileImagePicker.xcworkspace -scheme MMSProfileImagePicker-Example -sdk iphonesimulator PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=ios Simulator,name=iphone 6,OS=9.3' | xcpretty;
